/* Automatically generated by './build/bin/build-entry.js' */

import Label from '../packages/label/index.js';
import CalcInput from '../packages/calc-input/index.js';
import Cascader from '../packages/cascader/index.js';
import ExcelTable from '../packages/excel-table/index.js';
import Timedown from '../packages/timedown/index.js';
import MovingToolsbar from '../packages/moving-toolsbar/index.js';
import HigherSearch from '../packages/higher-search/index.js';
import RangeInput from '../packages/range-input/index.js';
import SelectInput from '../packages/select-input/index.js';
import TimeLine from '../packages/time-line/index.js';
import TagCheckbox from '../packages/tag-checkbox/index.js';
import InfiniteScroll from '../packages/infinite-scroll/index.js';
import Loading from '../packages/loading/index.js';
import MessageBox from '../packages/message-box/index.js';
import Message from '../packages/message/index.js';
import Notification from '../packages/notification/index.js';
import locale from 'cst-ui/src/locale';
import CollapseTransition from 'cst-ui/src/transitions/collapse-transition';

const components = [
  Label,
  CalcInput,
  Cascader,
  ExcelTable,
  Timedown,
  MovingToolsbar,
  HigherSearch,
  RangeInput,
  SelectInput,
  TimeLine,
  TagCheckbox,
  CollapseTransition
];

const install = function(Vue, opts = {}) {
  locale.use(opts.locale);
  locale.i18n(opts.i18n);

  components.forEach(component => {
    Vue.component(component.name, component);
  });

  Vue.use(InfiniteScroll);
  Vue.use(Loading.directive);

  Vue.prototype.$ELEMENT = {
    size: opts.size || '',
    zIndex: opts.zIndex || 2000
  };

  Vue.prototype.$loading = Loading.service;
  Vue.prototype.$msgbox = MessageBox;
  Vue.prototype.$alert = MessageBox.alert;
  Vue.prototype.$confirm = MessageBox.confirm;
  Vue.prototype.$prompt = MessageBox.prompt;
  Vue.prototype.$notify = Notification;
  Vue.prototype.$message = Message;

};

/* istanbul ignore if */
if (typeof window !== 'undefined' && window.Vue) {
  install(window.Vue);
}

export default {
  version: '0.2.2',
  locale: locale.use,
  i18n: locale.i18n,
  install,
  CollapseTransition,
  Loading,
  Label,
  CalcInput,
  Cascader,
  ExcelTable,
  Timedown,
  MovingToolsbar,
  HigherSearch,
  RangeInput,
  SelectInput,
  TimeLine,
  TagCheckbox,
  InfiniteScroll,
  MessageBox,
  Message,
  Notification
};
